In [1]:
import numpy as np

### Q-1 Create a null vector of size 10 but the fifth value which is 1.

In [22]:
arr = np.zeros(10)*np.nan
arr[4] = 1
arr

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

### Q-2 Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [9]:
def random_array(a,b):
    arr = np.random.random((a,b))
    return arr,np.mean(arr)
random_array(3,4)    

(array([[0.27579494, 0.29723587, 0.27647416, 0.83934084],
        [0.28111073, 0.79016567, 0.68611837, 0.38087316],
        [0.4061745 , 0.38094712, 0.84359709, 0.91567763]]),
 0.5311258382730392)

### Q-3 Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [19]:
def array2d(a,b):
    arr = np.ones((a,b))
    arr[1:-1,1:-1] = 0
    return arr
array2d(3,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [20]:
array2d(4,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [21]:
array2d(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Q-4 Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [30]:
arr = np.linspace(0.1,1,11,endpoint=False)
arr

array([0.1       , 0.18181818, 0.26363636, 0.34545455, 0.42727273,
       0.50909091, 0.59090909, 0.67272727, 0.75454545, 0.83636364,
       0.91818182])

### Q-5 Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [32]:
np.identity(3,4) # Not possible No of rows must be equal to no of columns

TypeError: Cannot interpret '4' as a data type

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### Q-6: Create a 5x5 matrix with row values ranging from 0 to 4.

In [44]:
arr = np.zeros((5,5))
ar = np.arange(5)
arr = arr+ar
arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

### Q-7: Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type. point = np.array([2,3]) 

In [73]:
arr = np.random.randint(1,100,size=(10,2))
point = np.array([2,3])
dist_arr = np.sqrt(np.sum((point-arr)**2,axis=1)).astype(int)
dist_arr

array([ 86,  57,  80,  30,  80,  49, 111,  93,  27,  60])

### Q-8: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [79]:
arr = np.arange(336).reshape(6,7,8)
arr

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

In [110]:
arr[1,5,4]

100

In [109]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### Q-9: Arrays
### You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.

In [111]:
ip = input("Provide num")

Provide num 1 2 3 4 -8 -10


In [116]:
arr = np.array(ip.split()[::-1],dtype=float)
arr

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### Q-10: Elements count
### Count the number of elements of a numpy array.

In [117]:
arr1 = np.array([])
arr2 = np.array([1, 2])

print(np.size(arr1))
print(np.size(arr2))

0
2


### Q-11: Softmax function
### Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

In [122]:
def softmax(arr):
    if type(arr) != np.ndarray:
        raise TypeError("Requires Numpy Array")
    elif arr.ndim > 1:
        raise TypeError("Requires 1D Array")
    s = np.sum(np.exp(arr))
    return np.exp(arr)/s
softmax(np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318]))

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

### Q-12: Vertical stack
### Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.

In [270]:
# Code for stacking of 1d and 2d array
import numpy as np

def vertical_stack(*arrays):
    # Check if all inputs are numpy arrays
    if not all(isinstance(arr, np.ndarray) for arr in arrays):
        return "Error: All inputs must be numpy arrays."

    # Get dimensions of all arrays
    dimensions = [arr.ndim for arr in arrays]

    # If all arrays are 1D, stack them as rows
    if all(dim == 1 for dim in dimensions):
        return np.vstack(arrays)

    # If all arrays are 2D, check for shape compatibility
    if all(dim == 2 for dim in dimensions):
        y_shapes = {arr.shape[1] for arr in arrays}
        if len(y_shapes) == 1:
            return np.vstack(arrays)
        else:
            return "Error: For 2D stacking, number of columns must be the same."

    # If mixing 1D and 2D arrays
    if 1 in dimensions and 2 in dimensions:
        ref_shape = None
        for arr in arrays:
            if arr.ndim == 2:
                ref_shape = arr.shape[1]
                break

        if ref_shape is None:
            return "Error: Invalid reference shape."

        for arr in arrays:
            if arr.ndim == 1:
                if arr.shape[0] != ref_shape:
                    return "Error: 1D array length must match the number of columns in 2D arrays."

        reshaped_arrays = [arr if arr.ndim == 2 else arr.reshape(1, -1) for arr in arrays]
        return np.vstack(reshaped_arrays)

    return "Error: Incompatible dimensions."

# Example usage:
a = np.array([1, 2, 3])  # 1D array
b = np.array([[4, 5, 6], [7, 8, 9]])  # 2D array
c = np.array([10, 11, 12])  # 1D array

print(vertical_stack(a, c))  # Stacking two 1D arrays
print(vertical_stack(b, a))  # Stacking 2D with 1D
print(vertical_stack(b, b))  # Stacking two 2D arrays

[[ 1  2  3]
 [10 11 12]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]


In [290]:
# My code for stacking of 1d and 2d and 3d array
def vstacking(*arrays):
    
    if not all(isinstance(arr,np.ndarray) for arr in arrays):
        return "Error: All input must be numpy array"

    # get dimensions of all array
    dimensions = [arr.ndim for arr in arrays]

    if all(dim == 1 for dim in dimensions):
        return np.vstack(arrays)

    if all(dim == 2 for dim in dimensions):
        y_shape = {arr.shape[1] for arr in arrays}
        if len(y_shape) == 1:
            return np.vstack(arrays)
        else:
            return "Error: For 2D stacking, number of columns must be the same."
    
    if all(dim == 3 for dim in dimensions):
        y_shape = {arr.shape[1] for arr in arrays}
        z_shape = {arr.shape[2] for arr in arrays}
        if len(y_shape)== 1 and len(z_shape) == 1:
            return np.vstack(arrays)
        else:
            return "Error: For 3D stacking, Y & Z dimensions must match."

    if 1 in dimensions and 2 in dimensions:
        ref_shape = None
        for arr in arrays:
            if arr.ndim == 2:
                ref_shape = arr.shape[1]
                break
        
        if ref_shape is None:
            return "Error: Invalid reference shape."

        for arr in arrays:
            if arr.ndim == 1:
                if arr.shape[0] != ref_shape:
                    return "Error: 1D array length must match the number of columns in 2D arrays."
        reshaped_arrays = [arr if arr.ndim == 2 else arr.reshape(1, -1) for arr in arrays]
        return np.vstack(reshaped_arrays)

    if 1 in dimensions and 2 in dimensions and 3 in dimension:
        return "Error: Incompatible dimensions."
    
    if 2 in dimensions and 3 in dimension:
        ref_shape_y = None
        ref_shape_z = None
        for arr in arrays:
            if arr.ndim == 3:
                ref_shape_y = arr.shape[1]
                ref_shape_z = arr.shape[2]
                break
        
        if ref_shape is None:
            return "Error: Invalid reference shape."

        for arr in arrays:
            if arr.ndim == 2:
                if arr.shape[0] != ref_shape_y or arr.shape[1] != ref_shape_z:
                    return "Error: For 2D-3D stacking, Y & Z dimensions must match."
        reshaped_arrays = [arr if arr.ndim == 3 else arr.reshape(1, arr.shape[0], arr.shape[1]) for arr in arrays]
        return np.vstack(reshaped_arrays)

    return "Error: Incompatible dimensions"

a = np.array([1, 2, 3])  # 1D
b = np.array([[4, 5, 6], [7, 8, 9]])  # 2D
c = np.array([10, 11, 12])  # 1D
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D
e = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # 3D

print(vstacking(a, c))   # Stacking two 1D arrays
print(vstacking(b, a))   # Stacking 2D with 1D
print(vstacking(b, b))   # Stacking two 2D arrays
print(vstacking(d, e))   # Stacking two 3D arrays
#print(vertical_stack(b, d))   # Stacking 2D with 3D (Error expected)
#print(vertical_stack(a, b, d)) # Stacking 1D, 2D, and 3D (Error expected)   

[[ 1  2  3]
 [10 11 12]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [288]:
# chatgpt code
import numpy as np

def vstacking(*arrays):
    if not all(isinstance(arr, np.ndarray) for arr in arrays):
        return "Error: All inputs must be numpy arrays."

    # Get dimensions of all arrays
    dimensions = [arr.ndim for arr in arrays]

    # Case 1: All 1D arrays → Stack as rows
    if all(dim == 1 for dim in dimensions):
        return np.vstack(arrays)

    # Case 2: All 2D arrays → Ensure same number of columns
    if all(dim == 2 for dim in dimensions):
        y_shapes = {arr.shape[1] for arr in arrays}
        if len(y_shapes) == 1:
            return np.vstack(arrays)
        return "Error: For 2D stacking, number of columns must be the same."

    # Case 3: All 3D arrays → Ensure same Y & Z dimensions
    if all(dim == 3 for dim in dimensions):
        y_shapes = {arr.shape[1] for arr in arrays}
        z_shapes = {arr.shape[2] for arr in arrays}
        if len(y_shapes) == 1 and len(z_shapes) == 1:
            return np.vstack(arrays)
        return "Error: For 3D stacking, Y & Z dimensions must match."

    # Case 4: Mixing 1D and 2D
    if 1 in dimensions and 2 in dimensions:
        ref_shape = None
        for arr in arrays:
            if arr.ndim == 2:
                ref_shape = arr.shape[1]
                break
        
        if ref_shape is None:
            return "Error: Invalid reference shape."

        for arr in arrays:
            if arr.ndim == 1 and arr.shape[0] != ref_shape:
                return "Error: 1D array length must match the number of columns in 2D arrays."

        reshaped_arrays = [arr if arr.ndim == 2 else arr.reshape(1, -1) for arr in arrays]
        return np.vstack(reshaped_arrays)

    # Case 5: Mixing 2D and 3D
    if 2 in dimensions and 3 in dimensions:
        ref_shape_y, ref_shape_z = None, None
        for arr in arrays:
            if arr.ndim == 3:
                ref_shape_y, ref_shape_z = arr.shape[1], arr.shape[2]
                break
        
        if ref_shape_y is None or ref_shape_z is None:
            return "Error: Invalid reference shape."

        for arr in arrays:
            if arr.ndim == 2:
                if arr.shape[0] != ref_shape_y or arr.shape[1] != ref_shape_z:
                    return "Error: For 2D-3D stacking, Y & Z dimensions must match."

        reshaped_arrays = [arr if arr.ndim == 3 else arr.reshape(1, arr.shape[0], arr.shape[1]) for arr in arrays]
        return np.vstack(reshaped_arrays)

    # Case 6: If 1D, 2D, and 3D are mixed → Invalid stacking
    return "Error: Incompatible dimensions."

# Example Tests:
a = np.array([1, 2, 3])  # 1D
b = np.array([[4, 5, 6], [7, 8, 9]])  # 2D
c = np.array([10, 11, 12])  # 1D
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D
e = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # 3D

print(vstacking(a, c))   # Stacking two 1D arrays
print(vstacking(b, a))   # Stacking 2D with 1D
print(vstacking(b, b))   # Stacking two 2D arrays
print(vstacking(d, e))   # Stacking two 3D arrays
#print(vertical_stack(b, d))   # Stacking 2D with 3D (Error expected)
#print(vertical_stack(a, b, d)) # Stacking 1D, 2D, and 3D (Error expected)    

[[ 1  2  3]
 [10 11 12]]
[[4 5 6]
 [7 8 9]
 [1 2 3]]
[[4 5 6]
 [7 8 9]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


### Q-13: Dates Create a python function named date_array that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: 2022-12-6. The end date should be included and for simplicity, choose dates from a same year.

In [373]:
import datetime
from functools import wraps

def input_decor(fun):
    @wraps(fun)
    def wrapper(*args):
        from_date = input("Please enter from date in YYYY-MM-DD format")
        to_date = input("Please enter to date in YYYY-MM-DD format")
        return fun(from_date,to_date)
        
    return wrapper

@input_decor
def date_array(from_date,to_date):
    try:
        date1 = datetime.datetime.strptime(from_date,"%Y-%m-%d")
        date2 = datetime.datetime.strptime(to_date,"%Y-%m-%d")
    except ValueError:
        return "Please enter correct dates in YYYY-MM-DD format only eg 2025-08-02"
    if date1 > date2:
        print("from date is after than to date. Please Enter correct dates")
        return date_array()
    else:
        curr = date1
        array = np.empty(0)
        while curr <= date2:
            array = np.append(array,(curr.strftime("%Y-%m-%d")))
            curr = curr + datetime.timedelta(1)
        return array
            
date_array()        

Please enter from date in YYYY-MM-DD format 2020-11-25
Please enter to date in YYYY-MM-DD format 2020-11-30


array(['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
       '2020-11-29', '2020-11-30'], dtype='<U32')

In [374]:
def date_array(start: str, end: str):
    if type(start) != str or type(end) != str:
        raise TypeError
        
    total_days_of_month = {"01": 31, "02": 28, "03": 31, "04":30, "05": 31, "06":30, "07":31, "08":31, "09":30, "10": 31, "11":30, "12":31}

    end = end.split("-")
    end_last = int(end[-1]) + 1
    
    # If the next day of end falls in the next month, account for that
    if total_days_of_month[end[-2]] < end_last:
        days_diff = end_last - total_days_of_month[end[-2]]
        end[-1] = f'0{days_diff}' if days_diff< 10 else f'{days_diff}'
        next_month = int(end[-2]) + 1
        end[-2] = f'0{next_month}' if next_month< 10 else f'{next_month}'
    else:
        end[-1] = f'0{end_last}' if end_last < 10 else f'{end_last}'
    end = "-".join(end)
    return np.arange(start, end, dtype="datetime64[D]")    # Use arange() to generate all dates between start and end 
date_array(start = '2020-12-25', end = '2021-01-02')

array(['2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28',
       '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01',
       '2021-01-02'], dtype='datetime64[D]')

In [376]:
import pandas as pd

def get_dates(from_date, to_date):
    return pd.date_range(start=from_date, end=to_date).strftime("%Y-%m-%d").tolist()

# Example usage
dates = get_dates("2025-01-01", "2025-01-05")
print(dates)

['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']


In [378]:
from datetime import datetime, timedelta

def get_dates(from_date, to_date):
    date1 = datetime.strptime(from_date, "%Y-%m-%d")
    date2 = datetime.strptime(to_date, "%Y-%m-%d")
    return [(date1 + timedelta(days=i)).strftime("%Y-%m-%d") for i in range((date2 - date1).days + 1)]

# Example usage
dates = get_dates("2025-01-01", "2025-01-05")
print(dates)


['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']


In [384]:
np.arange("2025-01-01", "2025-01-05",dtype="datetime64")

array(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04'],
      dtype='datetime64[D]')

### Q-14: Subtract the mean of each row from a matrix.

In [391]:
x = np.random.random((5,4))
x- np.mean(x,axis=1,keepdims=True)

array([[-0.37506661,  0.0466166 ,  0.04918897,  0.27926104],
       [ 0.01858414, -0.4119193 ,  0.34325564,  0.05007952],
       [ 0.22015668, -0.48058075,  0.25643942,  0.00398466],
       [ 0.31034533, -0.0542455 ,  0.18571865, -0.44181847],
       [-0.24076684, -0.21173515,  0.32553346,  0.12696852]])

In [397]:
arr = np.arange(12).reshape(3,4)
print(arr)
np.mean(arr,axis=1,keepdims=True)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1.5],
       [5.5],
       [9.5]])

In [398]:
arr - np.mean(arr,axis=1,keepdims=True)

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

### Q-15: Swap column-1 of array with column-2 in the array.

In [408]:
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [410]:
arr[:,[0,2,1,3]]

array([[ 0,  2,  1,  3],
       [ 4,  6,  5,  7],
       [ 8, 10,  9, 11]])

### Q-16: Replace odd elements in arrays with -1.

In [415]:
arr[arr%2 == 1] = -1
arr

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1]])

### Q-17: Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [425]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
[  for i,j in zip(a,b) ]

[6, 3, 1, 7, 8]

In [446]:
list(map((lambda x : a[x] if a[x] > b[x] else b[x] ),range(len(a))))

[6, 3, 1, 7, 8]

In [454]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
a[a<b] = b[b>a]
a

array([6, 3, 1, 7, 8])

### Q-18 Answer below asked questions on given array:
### Fetch Every alternate column of the array
### Normalise the given array
### https://en.wikipedia.org/wiki/Normalization_(statistics)

### There are different form of normalisation for this question use below formula.

In [ ]:
Xnormalized=X−Xmin/Xmax−Xmin

In [456]:
#Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9459, 5075, 5087, 6726, 7427],
       [9310, 8558, 2192, 9013, 3289],
       [3651, 1575, 3758,  495, 6997],
       [7023, 4709, 6344, 6226, 5534],
       [5228, 5108,  981, 5834, 5314],
       [4274, 2040, 6371, 1618, 1875],
       [6660, 2524,  895, 9513, 7461],
       [7004, 4439, 7163, 6979,  384]])

In [457]:
arr1[:,::2]

array([[9459, 5087, 7427],
       [9310, 2192, 3289],
       [3651, 3758, 6997],
       [7023, 6344, 5534],
       [5228,  981, 5314],
       [4274, 6371, 1875],
       [6660,  895, 7461],
       [7004, 7163,  384]])

In [460]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.99408478, 0.51385694, 0.51517143, 0.69470917, 0.77149743],
       [0.97776317, 0.89538832, 0.19805017, 0.94522949, 0.31821667],
       [0.35787052, 0.13046336, 0.36959141, 0.01215905, 0.72439479],
       [0.72724285, 0.47376492, 0.6528645 , 0.63993866, 0.56413627],
       [0.53061672, 0.51747179, 0.06539599, 0.59699858, 0.54003724],
       [0.42611458, 0.18139993, 0.65582211, 0.13517362, 0.16332567],
       [0.68747946, 0.23441779, 0.05597546, 1.        , 0.77522182],
       [0.72516157, 0.44418885, 0.7425786 , 0.72242305, 0.        ]])

In [462]:
(arr1 - np.min(arr1))/(np.max(arr1)-np.min(arr1))

array([[0.99408478, 0.51385694, 0.51517143, 0.69470917, 0.77149743],
       [0.97776317, 0.89538832, 0.19805017, 0.94522949, 0.31821667],
       [0.35787052, 0.13046336, 0.36959141, 0.01215905, 0.72439479],
       [0.72724285, 0.47376492, 0.6528645 , 0.63993866, 0.56413627],
       [0.53061672, 0.51747179, 0.06539599, 0.59699858, 0.54003724],
       [0.42611458, 0.18139993, 0.65582211, 0.13517362, 0.16332567],
       [0.68747946, 0.23441779, 0.05597546, 1.        , 0.77522182],
       [0.72516157, 0.44418885, 0.7425786 , 0.72242305, 0.        ]])

### Q-19: Write a function which will accept 2 arguments.


In [473]:
def nthlargest_num(arr,n):
    if not n <= len(arr):
        return "n must be less than length of array"
    return np.sort(arr)[-n]

arr=(12,34,40,7,1,0)
arr = np.array(arr)
nthlargest_num(arr,2)   

34

### Q-20: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.


In [ ]:
Input: a = np.array([1,2,3])
Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [477]:
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])