### Q-1: Create a random 3x4 matrix with value between 0-100. And perform below task

In [2]:
import numpy as np
arr = np.random.randint(0,100,12).reshape(3,4)
arr

array([[80, 99, 39, 37],
       [73, 66, 71, 74],
       [55, 59, 44, 27]])

In [6]:
# Sort this matrix. np.sort()
np.sort(arr)

array([[37, 39, 80, 99],
       [66, 71, 73, 74],
       [27, 44, 55, 59]])

In [10]:
# based on 2nd column
arr[:,1] # Extracting column for sorting

array([99, 66, 59])

In [9]:
arr[:,1].argsort() # give index by which if element arrange array will be sorted for second column

array([2, 1, 0], dtype=int64)

In [11]:
arr[[2,1,0]] # accessing element of array with fancy indexing for only column 1 sorting element

array([[55, 59, 44, 27],
       [73, 66, 71, 74],
       [80, 99, 39, 37]])

In [12]:
arr[arr[:,1].argsort()]

array([[55, 59, 44, 27],
       [73, 66, 71, 74],
       [80, 99, 39, 37]])

In [20]:
# based on row max- ascending
arr

array([[80, 99, 39, 37],
       [73, 66, 71, 74],
       [55, 59, 44, 27]])

In [19]:
arr[np.max(arr,axis=1).argsort()][::-1]

array([[80, 99, 39, 37],
       [73, 66, 71, 74],
       [55, 59, 44, 27]])

In [23]:
ar = np.array([[94, 87 ,26],
 [45, 73, 90],
 [70, 30, 81],
 [97,  7 ,83]])
ar

In [29]:
ar[np.max(ar,axis=1).argsort()]

array([[70, 30, 81],
       [45, 73, 90],
       [94, 87, 26],
       [97,  7, 83]])

In [ ]:
np.array(sorted)

In [30]:
(np.array(sorted(ar, key = lambda x: max(x))))

array([[70, 30, 81],
       [45, 73, 90],
       [94, 87, 26],
       [97,  7, 83]])

In [31]:
# Sort based on elements value
arr

array([[80, 99, 39, 37],
       [73, 66, 71, 74],
       [55, 59, 44, 27]])

In [34]:
np.sort(arr,axis=None).reshape(3,4)

array([[27, 37, 39, 44],
       [55, 59, 66, 71],
       [73, 74, 80, 99]])

### Q-2: There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.

In [43]:
# Approach 1
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks
extra_subject = np.array([41, 87, 72, 36, 92])
extra_subject = np.expand_dims(extra_subject,axis=1)

In [44]:
np.hstack((marks,extra_subject))

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [48]:
# Approach 2
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks
extra_subject = np.array([41, 87, 72, 36, 92])
extra_subject = np.expand_dims(extra_subject,axis=1)
np.concatenate((marks,extra_subject),axis=1)

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [49]:
# Add two new students marks in respective 5 subjects.(one subject added in above task)
marks1 = np.concatenate((marks,extra_subject),axis=1)
rec1 = np.array([77, 83, 98, 95, 89])
rec2 = np.array([92, 71, 52, 61, 53])
np.vstack((marks1,rec1,rec2))

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [53]:
marks1 = np.concatenate((marks,extra_subject),axis=1)
rec1 = np.expand_dims(np.array([77, 83, 98, 95, 89]),axis=0)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)
new = np.concatenate((marks1,rec1,rec2),axis=0)
new

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [52]:
# Add extra column with sum of all subjects(5-subjects) marks

In [63]:
sum_ar = np.sum(new,axis=1).reshape(-1,1)
sum_ar

array([[106],
       [328],
       [229],
       [234],
       [315],
       [442],
       [329]])

In [61]:
np.hstack((new,sum_ar))

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [66]:
final = np.concatenate((new,sum_ar),axis=1)

In [ ]:
# Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows

In [71]:
final[final[:,-1].argsort()[::-1]]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

In [74]:
np.array(sorted(final,key= lambda x:max(x),reverse=True))

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

### Q-3: Find unique arrays from a 2D array column wise and row wise.

In [76]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [78]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [79]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

### Q-4: Flip given 2-D array along both axes at the same time.

In [83]:
arr

array([[1, 2, 3, 3, 1, 1],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 8, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [81]:
np.flip(arr,axis=1)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [8, 8, 8, 3, 2, 1],
       [1, 1, 3, 3, 2, 1]])

In [82]:
np.flip(arr,axis=0)

array([[1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8],
       [0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1]])

In [84]:
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

In [85]:
arr = np.array([[1,2,3,3,1,1],
               [0,9,1,2,8,8],
               [1,2,3,8,8,8],
               [1,2,3,3,1,1],
               [0,6,1,2,11,7],
               [10,19,14,-2,8,-1]])
np.flip(arr)

array([[-1,  8, -2, 14, 19, 10],
       [ 7, 11,  2,  1,  6,  0],
       [ 1,  1,  3,  3,  2,  1],
       [ 8,  8,  8,  3,  2,  1],
       [ 8,  8,  2,  1,  9,  0],
       [ 1,  1,  3,  3,  2,  1]])

### Q-5: Get row numbers of NumPy array having element larger than X.

In [101]:
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])
X = 6
np.unique(np.where(arr>X)[0])

array([1, 3], dtype=int64)

In [106]:
np.where(np.any(arr > X, axis = 1))

(array([1, 3], dtype=int64),)

### Q-6: How to convert an array of arrays into a flat 1d array?

In [114]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
np.concatenate((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.hstack((arr1,arr2,arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Q-7: You are given a array. You have to find the minimum and maximum array element and remove that from the array.

In [168]:
np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
max_element = arr.argmax()
min_element = arr.argmin()
print(arr.max(), arr.min())
arr = np.delete(arr, max_element, axis = 1)
arr = np.delete(arr, min_element, axis = 1)
print(arr.max(), arr.min())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
998 103
997 117


### Q-8: You are given an arrays. You have to limit this array's elements between 100 to 200.  arr∈[100,200] . So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.


In [174]:
arr = np.random.randint(0, 2000, 500)
np.cumsum(np.sort(np.clip(arr,100,200)))

array([  100,   200,   300,   400,   500,   600,   700,   800,   900,
        1000,  1100,  1200,  1300,  1400,  1503,  1607,  1713,  1820,
        1928,  2037,  2146,  2257,  2375,  2495,  2619,  2744,  2878,
        3019,  3172,  3334,  3502,  3672,  3843,  4018,  4196,  4374,
        4552,  4738,  4924,  5113,  5303,  5497,  5691,  5891,  6091,
        6291,  6491,  6691,  6891,  7091,  7291,  7491,  7691,  7891,
        8091,  8291,  8491,  8691,  8891,  9091,  9291,  9491,  9691,
        9891, 10091, 10291, 10491, 10691, 10891, 11091, 11291, 11491,
       11691, 11891, 12091, 12291, 12491, 12691, 12891, 13091, 13291,
       13491, 13691, 13891, 14091, 14291, 14491, 14691, 14891, 15091,
       15291, 15491, 15691, 15891, 16091, 16291, 16491, 16691, 16891,
       17091, 17291, 17491, 17691, 17891, 18091, 18291, 18491, 18691,
       18891, 19091, 19291, 19491, 19691, 19891, 20091, 20291, 20491,
       20691, 20891, 21091, 21291, 21491, 21691, 21891, 22091, 22291,
       22491, 22691,

### Q-9: You are given a array ( arr∈[0,1] ). First you have round off the elements upto 3 decimal places and compare that

In [179]:
arr = np.round(np.random.random(100),3)
arr

array([0.013, 0.986, 0.517, 0.023, 0.249, 0.429, 0.836, 0.524, 0.092,
       0.892, 0.35 , 0.93 , 0.549, 0.365, 0.901, 0.776, 0.836, 0.769,
       0.448, 0.807, 0.62 , 0.559, 0.101, 0.899, 0.341, 0.361, 0.067,
       0.673, 0.347, 0.434, 0.648, 0.177, 0.573, 0.359, 0.237, 0.197,
       0.616, 0.419, 0.532, 0.445, 0.663, 0.719, 0.378, 0.414, 0.769,
       0.583, 0.985, 0.39 , 0.604, 0.323, 0.707, 0.75 , 0.875, 0.232,
       0.357, 0.029, 0.87 , 0.868, 0.324, 0.027, 0.543, 0.756, 0.629,
       0.869, 0.721, 0.39 , 0.015, 0.83 , 0.36 , 0.386, 0.802, 0.424,
       0.506, 0.985, 0.111, 0.378, 0.091, 0.36 , 0.385, 0.809, 0.942,
       0.331, 0.331, 0.153, 0.102, 0.387, 0.562, 0.379, 0.108, 0.001,
       0.725, 0.256, 0.753, 0.973, 0.14 , 0.053, 0.775, 0.244, 0.326,
       0.915])

In [181]:
np.min(arr) == np.percentile(arr,0)

True

In [182]:
np.max(arr) == np.percentile(arr,100)

True

In [184]:
np.percentile(arr,51) - np.percentile(arr,50)

0.006970000000000032